:- dynamic(pemain_list/1).
:- dynamic(urutan_pemain/1).
:- dynamic(giliran_sekarang/1).
:- dynamic(kartu_tangan/2).
:- dynamic(discard_top/1).
:- dynamic(arah_permainan/1).
:- dynamic(warna_sebelum_wild/1).
:- dynamic(status_uni/1).
:- dynamic(warna_aktif/1).
:- dynamic(efek_kartu_pending/1).
:- dynamic(tumpukan_dek/1).
:- dynamic(kartu_aksi_terakhir/1).
:- dynamic(kartu_tersembunyi/2).
:- dynamic(mode_permainan/1).
:- dynamic(tim/2).
:- dynamic(sudah_swap/1).

%Include modul
:- include('state.pl').
:- include('setup.pl').
:- include('fungsi.pl').
:- include('aksi.pl').
:- include('perintah.pl').
:- include('fileio.pl').